spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mastersThesis
    username: postgres
    password: postgres
---
spring:
  config:
    activate:
      on-profile: flyway
  liquibase:
    enabled: false
  flyway:
    enabled: true
    clean-disabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: liquibase
  flyway:
    enabled: false
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
